/* 
 * ⚠️ DO NOT USE THIS FILE ⚠️
 * 
 * This file is DEPRECATED and has been moved to legacy.
 * 
 * DO NOT EDIT THIS FILE. DO NOT REFERENCE THIS FILE.
 * 
 * The frontend uses src/neonApi.js which connects directly to Neon database.
 * This Express server was never actually used and is kept only for reference.
 * 
 * If you need to edit database logic, edit src/neonApi.js instead.
 * 
 * ⚠️ DO NOT USE THIS FILE ⚠️
 */

const express = require('express');
const cors = require('cors');
const path = require('path');
const dotenv = require('dotenv');
dotenv.config({ path: path.resolve(__dirname, '..', '.env') });
dotenv.config({ path: path.resolve(__dirname, '..', '..', '.env') });

// Require POSTGRES_URL - no local fallback
if (!process.env.POSTGRES_URL && !process.env.DATABASE_URL) {
  console.error('ERROR: POSTGRES_URL or DATABASE_URL must be set in environment variables');
  console.error('This application requires Vercel Postgres/Neon database connection');
  process.exit(1);
}

// Map and normalize DB URL before importing vercel client
(function normalizeDbUrl() {
  let url = process.env.POSTGRES_URL || process.env.DATABASE_URL;
  if (/sslmode=$/.test(url)) url += 'require';
  if (!/([?&])sslmode=/.test(url)) url += (url.includes('?') ? '&' : '?') + 'sslmode=require';
  process.env.POSTGRES_URL = url;
})();

const { sql } = require('@vercel/postgres');

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());
app.use(express.json());

// Test database connection
async function testConnection() {
  try {
    await sql`SELECT NOW()`;
    console.log('Connected to Vercel Postgres database');
  } catch (err) {
    console.error('Database connection error:', err);
    console.error('Make sure POSTGRES_URL or DATABASE_URL is set correctly');
    process.exit(1);
  }
}

testConnection();

// Helper function to execute queries using @vercel/postgres
// @vercel/postgres uses template literals natively, but we support both template literals and parameterized queries
// For parameterized queries ($1, $2, etc), we use sql.query if available
async function executeQuery(query, params = []) {
  // If no params, use template literal directly
  if (!params || params.length === 0) {
    // Convert regular string query to template literal
    return await sql.query(query);
  }
  
  // For parameterized queries, check if sql.query exists
  // Some versions of @vercel/postgres support sql.query() with parameters
  if (typeof sql.query === 'function') {
    try {
      return await sql.query(query, params);
    } catch (err) {
      // If sql.query fails, it might not support parameters
      // Fall through to manual conversion
      console.warn('sql.query() with parameters failed, attempting manual conversion');
    }
  }
  
  // Manual conversion: replace $1, $2, etc with actual values
  // This is a basic implementation - for production, consider using a proper query builder
  let convertedQuery = query;
  params.forEach((param, index) => {
    const placeholder = `$${index + 1}`;
    const value = typeof param === 'string' ? `'${param.replace(/'/g, "''")}'` : param;
    convertedQuery = convertedQuery.replace(new RegExp(`\\${placeholder}(?!\\d)`, 'g'), value);
  });
  
  return await sql.query(convertedQuery);
}

// Routes
// Book missions endpoints

// List all book missions
app.get('/api/book-missions', async (req, res) => {
  try {
    const result = await sql`SELECT * FROM book_missions ORDER BY id`;
    res.json(result.rows || result);
  } catch (err) {
    console.error('Error fetching book missions:', err);
    res.status(500).json({ error: 'Failed to fetch book missions' });
  }
});

// Shared assignment logic for book missions
async function assignBookMissions() {
  // Get available agents per team
  const redUsersResult = await executeQuery('SELECT id FROM users WHERE team = $1 AND ishere = true', ['red']);
  const blueUsersResult = await executeQuery('SELECT id FROM users WHERE team = $1 AND ishere = true', ['blue']);
  const redUsers = (redUsersResult.rows || redUsersResult).map(u => u.id);
  const blueUsers = (blueUsersResult.rows || blueUsersResult).map(u => u.id);

  if (redUsers.length === 0 || blueUsers.length === 0) {
    return { assigned: 0, reason: 'Need at least one available agent on both teams' };
  }

  // Fetch all book missions with prior assignees
  const missionsResult = await executeQuery('SELECT id, previous_reds, previous_blues FROM book_missions ORDER BY id');
  const missions = missionsResult.rows || missionsResult;

  // Helper to pick a random element
  const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];

  // Current assignment counts per user (to enforce max 3 missions per agent)
  const redCountsRes = await executeQuery(
    `SELECT assigned_red AS user_id, COUNT(*)::int AS cnt
     FROM book_missions WHERE assigned_red IS NOT NULL GROUP BY assigned_red`
  );
  const blueCountsRes = await executeQuery(
    `SELECT assigned_blue AS user_id, COUNT(*)::int AS cnt
     FROM book_missions WHERE assigned_blue IS NOT NULL GROUP BY assigned_blue`
  );
  const redCountMap = new Map((redCountsRes.rows || redCountsRes).map(r => [r.user_id, r.cnt]));
  const blueCountMap = new Map((blueCountsRes.rows || blueCountsRes).map(r => [r.user_id, r.cnt]));

  let updates = 0;
  // Assign each mission to one random red and one random blue, excluding prior assignees
  for (const m of missions) {
    const prevReds = Array.isArray(m.previous_reds) ? m.previous_reds : [];
    const prevBlues = Array.isArray(m.previous_blues) ? m.previous_blues : [];

    const eligibleReds = redUsers.filter(id => !prevReds.includes(id) && (redCountMap.get(id) || 0) < 3);
    const eligibleBlues = blueUsers.filter(id => !prevBlues.includes(id) && (blueCountMap.get(id) || 0) < 3);

    const redId = eligibleReds.length ? pick(eligibleReds) : null;
    const blueId = eligibleBlues.length ? pick(eligibleBlues) : null;

    // Only update columns we have eligible users for
    if (redId !== null && blueId !== null) {
      await executeQuery(
        `UPDATE book_missions
         SET assigned_red = $1,
             assigned_blue = $2,
             previous_reds = array_append(COALESCE(previous_reds, ARRAY[]::integer[]), $1),
             previous_blues = array_append(COALESCE(previous_blues, ARRAY[]::integer[]), $2)
         WHERE id = $3`,
        [redId, blueId, m.id]
      );
      updates++;
      redCountMap.set(redId, (redCountMap.get(redId) || 0) + 1);
      blueCountMap.set(blueId, (blueCountMap.get(blueId) || 0) + 1);
    } else if (redId !== null) {
      await executeQuery(
        `UPDATE book_missions
         SET assigned_red = $1,
             previous_reds = array_append(COALESCE(previous_reds, ARRAY[]::integer[]), $1)
         WHERE id = $2`,
        [redId, m.id]
      );
      updates++;
      redCountMap.set(redId, (redCountMap.get(redId) || 0) + 1);
    } else if (blueId !== null) {
      await executeQuery(
        `UPDATE book_missions
         SET assigned_blue = $1,
             previous_blues = array_append(COALESCE(previous_blues, ARRAY[]::integer[]), $1)
         WHERE id = $2`,
        [blueId, m.id]
      );
      updates++;
      blueCountMap.set(blueId, (blueCountMap.get(blueId) || 0) + 1);
    }
  }

  return { assigned: updates };
}

// HTTP endpoint to trigger assignment (use with Vercel Cron in production)
app.post('/api/book-missions/assign-random', async (req, res) => {
  try {
    const result = await assignBookMissions();
    res.json({ message: `Assignments updated`, ...result });
  } catch (err) {
    console.error('Error assigning book missions:', err);
    res.status(500).json({ error: 'Failed to assign book missions' });
  }
});

// Optional: local scheduler to periodically assign missions (not reliable on serverless)
const intervalMinutes = Number(process.env.BOOK_MISSION_INTERVAL_MINUTES || 15);
if (process.env.ENABLE_BOOK_MISSION_SCHEDULER === 'true') {
  setInterval(() => {
    assignBookMissions().catch(err => console.error('Scheduled book mission assignment failed:', err));
  }, intervalMinutes * 60 * 1000);
}

// Get book missions assigned to a specific agent
app.get('/api/book-missions/for-agent/:agentId', async (req, res) => {
  try {
    const { agentId } = req.params;
    const idNum = Number(agentId);
    const result = await executeQuery(
      'SELECT id, book, clue_red, clue_blue, assigned_red, assigned_blue FROM book_missions WHERE assigned_red = $1 OR assigned_blue = $1 ORDER BY id',
      [idNum]
    );
    const rows = result.rows || result;
    const payload = rows.map(r => {
      if (r.assigned_red === idNum) {
        return { id: r.id, book: r.book, clue: r.clue_red, color: 'red' };
      }
      return { id: r.id, book: r.book, clue: r.clue_blue, color: 'blue' };
    });
    res.json(payload);
  } catch (err) {
    console.error('Error fetching book missions for agent:', err);
    res.status(500).json({ error: 'Failed to fetch book missions for agent' });
  }
});


// Get all users
app.get('/api/users', async (req, res) => {
  try {
    const result = await executeQuery('SELECT id, firstname, lastname, team, alias_1, alias_2, ishere FROM users ORDER BY firstname');
    res.json(result.rows || result);
  } catch (err) {
    console.error('Error fetching users:', err);
    res.status(500).json({ error: 'Failed to fetch users' });
  }
});

// Get random user alias
app.get('/api/users/random', async (req, res) => {
  console.log('Random user request received from:', req.ip);
  try {
    const result = await executeQuery('SELECT alias_1, alias_2 FROM users WHERE ishere = true ORDER BY RANDOM() LIMIT 1');
    console.log('Random user query result:', result.rows?.[0] || result[0]);
    const user = result.rows?.[0] || result[0];
    if (user) {
      res.json({ 
        codename: `${user.alias_1} ${user.alias_2}`,
        alias_1: user.alias_1,
        alias_2: user.alias_2
      });
    } else {
      res.json({ codename: 'AGENT', alias_1: 'Unknown', alias_2: 'Agent' });
    }
  } catch (err) {
    console.error('Error fetching random user:', err);
    res.status(500).json({ error: 'Failed to fetch random user' });
  }
});

// Get users by team
app.get('/api/users/team/:team', async (req, res) => {
  try {
    const { team } = req.params;
    const result = await executeQuery('SELECT id, firstname, lastname, team, alias_1, alias_2 FROM users WHERE team = $1 AND ishere = true ORDER BY firstname', [team]);
    res.json(result.rows || result);
  } catch (err) {
    console.error('Error fetching users by team:', err);
    res.status(500).json({ error: 'Failed to fetch users by team' });
  }
});

// Get random team member from specified team
app.get('/api/users/team/:team/random', async (req, res) => {
  try {
    const { team } = req.params;
    
    // Validate team parameter
    if (!['red', 'blue'].includes(team)) {
      return res.status(400).json({ error: 'Team must be "red" or "blue"' });
    }
    
    const result = await executeQuery(
      'SELECT firstname, lastname, alias_1, alias_2 FROM users WHERE team = $1 AND ishere = true ORDER BY RANDOM() LIMIT 1',
      [team]
    );
    
    const users = result.rows || result;
    if (users.length === 0) {
      return res.status(404).json({ error: `No users found for team ${team}` });
    }
    
    const user = users[0];
    res.json({
      firstname: user.firstname,
      lastname: user.lastname,
      alias_1: user.alias_1,
      alias_2: user.alias_2,
      codename: `${user.alias_1} ${user.alias_2}` // For backward compatibility
    });
  } catch (err) {
    console.error('Error fetching random team member:', err);
    res.status(500).json({ error: 'Failed to fetch random team member' });
  }
});

// Get team points
app.get('/api/teams/:team/points', async (req, res) => {
  try {
    const { team } = req.params;
    const result = await executeQuery('SELECT points FROM teams WHERE name = $1', [team]);
    const teams = result.rows || result;
    res.json(teams[0] || { points: 0 });
  } catch (err) {
    console.error('Error fetching team points:', err);
    res.status(500).json({ error: 'Failed to fetch team points' });
  }
});

// Update team points
app.put('/api/teams/:team/points', async (req, res) => {
  try {
    const { team } = req.params;
    const { points } = req.body;
    const result = await executeQuery('UPDATE teams SET points = $1 WHERE name = $2 RETURNING *', [points, team]);
    const teams = result.rows || result;
    res.json(teams[0]);
  } catch (err) {
    console.error('Error updating team points:', err);
    res.status(500).json({ error: 'Failed to update team points' });
  }
});

// Get all missions
app.get('/api/missions', async (req, res) => {
  try {
    const result = await executeQuery('SELECT * FROM missions ORDER BY id');
    res.json(result.rows || result);
  } catch (err) {
    console.error('Error fetching missions:', err);
    res.status(500).json({ error: 'Failed to fetch missions' });
  }
});

// Get available missions (not assigned)
app.get('/api/missions/available', async (req, res) => {
  try {
    const result = await executeQuery('SELECT * FROM missions WHERE assigned_now = false ORDER BY id');
    res.json(result.rows || result);
  } catch (err) {
    console.error('Error fetching available missions:', err);
    res.status(500).json({ error: 'Failed to fetch available missions' });
  }
});

// Refresh missions for dashboard (assigns missions to all users until each has 3)
app.post('/api/missions/refresh', async (req, res) => {
  try {
    console.log('Refreshing missions for all users...');
    
    // First, repopulate the database by resetting ALL missions to available status
    await executeQuery(`
      UPDATE missions 
      SET completed = false, assigned_now = false, assigned_agent = null, 
          past_assigned_agents = array[]::integer[], mission_expires = null
    `);
    
    // Reset object_missions to available status
    await executeQuery(`
      UPDATE object_missions 
      SET completed = false, assigned_now = false, assigned_agent = null, 
          past_assigned_agents = array[]::integer[]
    `);
    
    // Reset passphrase_missions to available status
    await executeQuery(`
      UPDATE passphrase_missions 
      SET completed = false, assigned_receiver = null, assigned_sender_1 = null, 
          assigned_sender_2 = null, previous_receivers = array[]::integer[], 
          previous_senders = array[]::integer[]
    `);
    
    // Reset book_missions to available status
    await executeQuery(`
      UPDATE book_missions 
      SET red_completed = false, blue_completed = false, assigned_red = null, 
          assigned_blue = null, previous_reds = array[]::integer[], 
          previous_blues = array[]::integer[]
    `);
    
    console.log('Database repopulated - all missions reset to available');
    
    // Get all users who are present
    const usersResult = await executeQuery('SELECT id, team FROM users WHERE ishere = true ORDER BY id');
    const users = (usersResult.rows || usersResult);
    
    if (users.length === 0) {
      return res.status(400).json({ error: 'No users available' });
    }
    
    // Track mission counts and types per user
    const missionCounts = new Map();
    const missionTypesByUser = new Map(); // { userId: ['book', 'passphrase', ...] }
    users.forEach(user => {
      missionCounts.set(user.id, 0);
      missionTypesByUser.set(user.id, []);
    });
    
    const assignedMissionsByUser = new Map();
    users.forEach(user => assignedMissionsByUser.set(user.id, []));
    
    // Helper function to pick random element
    const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
    
    // Helper function to get available users for assignment
    const getAvailableUsers = (excludeIds = []) => {
      return users.filter(u => 
        !excludeIds.includes(u.id) && 
        (missionCounts.get(u.id) || 0) < 3
      );
    };
    
    // Helper function to refresh available missions from database
    const refreshAvailableMissions = async () => {
      const bookResult = await executeQuery('SELECT * FROM book_missions WHERE assigned_red IS NULL OR assigned_blue IS NULL ORDER BY RANDOM()');
      const passphraseResult = await executeQuery('SELECT * FROM passphrase_missions WHERE assigned_receiver IS NULL AND assigned_sender_1 IS NULL AND assigned_sender_2 IS NULL ORDER BY RANDOM()');
      return {
        book: (bookResult.rows || bookResult),
        passphrase: (passphraseResult.rows || passphraseResult)
      };
    };
    
    // Helper function to determine which mission type user needs
    const getNeededMissionType = (userId) => {
      const userMissions = missionTypesByUser.get(userId) || [];
      const bookCount = userMissions.filter(t => t === 'book').length;
      const passphraseCount = userMissions.filter(t => t === 'passphrase').length;
      
      // If user has 0 missions, prefer giving them a book mission first (2-person)
      // If user has 1 mission and it's book, give them passphrase
      // If user has 1 mission and it's passphrase, give them book
      // If user has 2 missions, give them the type they have fewer of
      
      if (userMissions.length === 0) {
        return 'book'; // Start with book missions
      } else if (userMissions.length === 1) {
        return userMissions[0] === 'book' ? 'passphrase' : 'book';
      } else if (userMissions.length === 2) {
        return bookCount < passphraseCount ? 'book' : 'passphrase';
      }
      return null; // User has 3 missions already
    };
    
    let availableMissions = await refreshAvailableMissions();
    
    // Main assignment loop - iterate until all users have 3 missions
    let iterations = 0;
    const maxIterations = users.length * 10; // Safety limit
    
    while (iterations < maxIterations) {
      iterations++;
      
      // Find users who still need missions
      const usersNeedingMissions = users.filter(u => (missionCounts.get(u.id) || 0) < 3);
      
      if (usersNeedingMissions.length === 0) {
        break; // All users have 3 missions
      }
      
      // Refresh available missions periodically
      if (iterations % 5 === 0) {
        availableMissions = await refreshAvailableMissions();
      }
      
      // Try to assign a mission to a random user who needs one
      const user = pick(usersNeedingMissions);
      const neededType = getNeededMissionType(user.id);
      
      let assigned = false;
      
      // Randomly choose between book and passphrase if both are available and user could use either
      // This ensures a mix of both types throughout the assignment process
      const canUseBook = neededType === 'book' || (neededType !== 'passphrase' && availableMissions.book.length > 0);
      const canUsePassphrase = neededType === 'passphrase' || (neededType !== 'book' && availableMissions.passphrase.length > 0);
      
      let missionTypeToTry = neededType;
      
      // If user could use either type, randomly choose to ensure mix
      if (canUseBook && canUsePassphrase && availableMissions.book.length > 0 && availableMissions.passphrase.length > 0) {
        missionTypeToTry = Math.random() < 0.5 ? 'book' : 'passphrase';
      } else if (canUsePassphrase && availableMissions.passphrase.length > 0) {
        missionTypeToTry = 'passphrase';
      } else if (canUseBook && availableMissions.book.length > 0) {
        missionTypeToTry = 'book';
      }
      
      // Try to assign based on chosen type
      if (missionTypeToTry === 'book' && availableMissions.book.length > 0) {
        // Find a book mission for this user's team
        let bookMission = availableMissions.book.find(m => {
          if (user.team === 'red' && m.assigned_red === null) return true;
          if (user.team === 'blue' && m.assigned_blue === null) return true;
          return false;
        });
        
        // If no team-specific match, find any book mission needing assignment
        if (!bookMission) {
          bookMission = availableMissions.book.find(m => 
            (m.assigned_red === null && user.team === 'red') || 
            (m.assigned_blue === null && user.team === 'blue')
          );
        }
        
        // If still no match, find any book mission that needs both assignments
        if (!bookMission) {
          bookMission = availableMissions.book.find(m => 
            m.assigned_red === null || m.assigned_blue === null
          );
        }
        
        if (bookMission) {
          // Find a partner for the opposite team
          const oppositeTeam = user.team === 'red' ? 'blue' : 'red';
          const availableOppositeTeam = getAvailableUsers([user.id]).filter(u => u.team === oppositeTeam);
          
          if (availableOppositeTeam.length > 0) {
            const partner = pick(availableOppositeTeam);
            
            // Assign both users
            if (user.team === 'red') {
              await executeQuery(`
                UPDATE book_missions 
                SET assigned_red = $1, previous_reds = array_append(COALESCE(previous_reds, ARRAY[]::integer[]), $1),
                    assigned_blue = $2, previous_blues = array_append(COALESCE(previous_blues, ARRAY[]::integer[]), $2)
                WHERE id = $3
              `, [user.id, partner.id, bookMission.id]);
            } else {
              await executeQuery(`
                UPDATE book_missions 
                SET assigned_blue = $1, previous_blues = array_append(COALESCE(previous_blues, ARRAY[]::integer[]), $1),
                    assigned_red = $2, previous_reds = array_append(COALESCE(previous_reds, ARRAY[]::integer[]), $2)
                WHERE id = $3
              `, [user.id, partner.id, bookMission.id]);
            }
            
            missionCounts.set(user.id, (missionCounts.get(user.id) || 0) + 1);
            missionCounts.set(partner.id, (missionCounts.get(partner.id) || 0) + 1);
            missionTypesByUser.get(user.id).push('book');
            missionTypesByUser.get(partner.id).push('book');
            
            assignedMissionsByUser.get(user.id).push({ ...bookMission, mission_type: 'book' });
            assignedMissionsByUser.get(partner.id).push({ ...bookMission, mission_type: 'book' });
            
            // Remove from available
            availableMissions.book = availableMissions.book.filter(m => m.id !== bookMission.id);
            assigned = true;
          }
        }
      }
      
      // Try to assign passphrase mission if that's what was chosen or as fallback
      if ((missionTypeToTry === 'passphrase' || !assigned) && availableMissions.passphrase.length > 0) {
        const passphraseMission = availableMissions.passphrase[0];
        const availableForSenders = getAvailableUsers([user.id]);
        
        if (availableForSenders.length >= 2) {
          const sender1 = pick(availableForSenders);
          const remainingAfterSender1 = availableForSenders.filter(u => u.id !== sender1.id);
          const sender2 = pick(remainingAfterSender1);
          
          await executeQuery(`
            UPDATE passphrase_missions 
            SET assigned_receiver = $1, 
                assigned_sender_1 = $2,
                assigned_sender_2 = $3,
                previous_receivers = array_append(COALESCE(previous_receivers, ARRAY[]::integer[]), $1),
                previous_senders = array_append(array_append(COALESCE(previous_senders, ARRAY[]::integer[]), $2), $3)
            WHERE id = $4
          `, [user.id, sender1.id, sender2.id, passphraseMission.id]);
          
          missionCounts.set(user.id, (missionCounts.get(user.id) || 0) + 1);
          missionCounts.set(sender1.id, (missionCounts.get(sender1.id) || 0) + 1);
          missionCounts.set(sender2.id, (missionCounts.get(sender2.id) || 0) + 1);
          
          missionTypesByUser.get(user.id).push('passphrase');
          missionTypesByUser.get(sender1.id).push('passphrase');
          missionTypesByUser.get(sender2.id).push('passphrase');
          
          assignedMissionsByUser.get(user.id).push({ ...passphraseMission, mission_type: 'passphrase' });
          assignedMissionsByUser.get(sender1.id).push({ ...passphraseMission, mission_type: 'passphrase' });
          assignedMissionsByUser.get(sender2.id).push({ ...passphraseMission, mission_type: 'passphrase' });
          
          availableMissions.passphrase = availableMissions.passphrase.filter(m => m.id !== passphraseMission.id);
          assigned = true;
        }
      }
      
      // If no assignment was made this iteration, break to avoid infinite loop
      if (!assigned && (availableMissions.book.length === 0 && availableMissions.passphrase.length === 0)) {
        console.log('No more missions available and no assignments made');
        break;
      }
    }
    
    // Convert to response format
    const missionAssignments = {};
    assignedMissionsByUser.forEach((missions, userId) => {
      missionAssignments[userId] = missions;
    });
    
    console.log(`Successfully assigned missions to ${users.length} users`);
    res.json(missionAssignments);
  } catch (err) {
    console.error('Error refreshing missions:', err);
    res.status(500).json({ error: 'Failed to refresh missions' });
  }
});

// Assign passphrase missions - using EXACT same pattern as book missions
async function assignPassphraseMissions() {
  // Get available agents - same as book missions
  const usersResult = await executeQuery('SELECT id FROM users WHERE ishere = true', []);
  const users = (usersResult.rows || usersResult).map(u => u.id);

  if (users.length < 3) {
    return { assigned: 0, reason: 'Need at least 3 available agents' };
  }

  // Fetch all passphrase missions - same pattern as book missions
  const missionsResult = await executeQuery('SELECT id, previous_receivers, previous_senders FROM passphrase_missions ORDER BY id');
  const missions = missionsResult.rows || missionsResult;

  // Helper to pick a random element - same as book missions
  const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];

  // Current assignment counts per user - same pattern as book missions
  const receiverCountsRes = await executeQuery(
    `SELECT assigned_receiver AS user_id, COUNT(*)::int AS cnt
     FROM passphrase_missions WHERE assigned_receiver IS NOT NULL GROUP BY assigned_receiver`
  );
  const senderCountsRes = await executeQuery(
    `SELECT assigned_sender_1 AS user_id, COUNT(*)::int AS cnt
     FROM passphrase_missions WHERE assigned_sender_1 IS NOT NULL GROUP BY assigned_sender_1
     UNION ALL
     SELECT assigned_sender_2 AS user_id, COUNT(*)::int AS cnt
     FROM passphrase_missions WHERE assigned_sender_2 IS NOT NULL GROUP BY assigned_sender_2`
  );
  
  const receiverCounts = receiverCountsRes.rows || receiverCountsRes;
  const senderCounts = senderCountsRes.rows || senderCountsRes;
  const receiverCountMap = new Map(receiverCounts.map(r => [r.user_id, Number(r.cnt)]));
  const senderCountMap = new Map();
  senderCounts.forEach(s => {
    senderCountMap.set(s.user_id, (senderCountMap.get(s.user_id) || 0) + Number(s.cnt));
  });

  let updates = 0;
  // Assign each mission to one receiver and two senders - EXACT same pattern as book missions
  for (const m of missions) {
    const prevReceivers = Array.isArray(m.previous_receivers) ? m.previous_receivers : [];
    const prevSenders = Array.isArray(m.previous_senders) ? m.previous_senders : [];

    // Get eligible users - same logic as book missions but for 3 people
    const eligibleReceivers = users.filter(id => 
      !prevReceivers.includes(id) && 
      (receiverCountMap.get(id) || 0) < 3
    );
    
    const eligibleSenders = users.filter(id => 
      !prevSenders.includes(id) && 
      (senderCountMap.get(id) || 0) < 3
    );

    const receiverId = eligibleReceivers.length ? pick(eligibleReceivers) : null;
    const availableSenders = eligibleSenders.filter(id => id !== receiverId);
    
    if (receiverId !== null && availableSenders.length >= 2) {
      const sender1 = pick(availableSenders);
      const sender2 = pick(availableSenders.filter(id => id !== sender1));
      
      // Assign receiver and two senders - EXACT same UPDATE pattern as book missions
      await executeQuery(
        `UPDATE passphrase_missions
         SET assigned_receiver = $1,
             assigned_sender_1 = $2,
             assigned_sender_2 = $3,
             previous_receivers = array_append(COALESCE(previous_receivers, ARRAY[]::integer[]), $1),
             previous_senders = array_append(array_append(COALESCE(previous_senders, ARRAY[]::integer[]), $2), $3)
         WHERE id = $4`,
        [receiverId, sender1, sender2, m.id]
      );
      updates++;
      receiverCountMap.set(receiverId, (receiverCountMap.get(receiverId) || 0) + 1);
      senderCountMap.set(sender1, (senderCountMap.get(sender1) || 0) + 1);
      senderCountMap.set(sender2, (senderCountMap.get(sender2) || 0) + 1);
    }
  }

  return { assigned: updates };
}

// HTTP endpoint to trigger passphrase assignment - same pattern as book missions
app.post('/api/passphrase-missions/assign-random', async (req, res) => {
  try {
    const result = await assignPassphraseMissions();
    res.json({ message: `Assignments updated`, ...result });
  } catch (err) {
    console.error('Error assigning passphrase missions:', err);
    res.status(500).json({ error: 'Failed to assign passphrase missions' });
  }
});

// Test endpoint for passphrase mission assignments only
app.post('/api/missions/test-passphrase', async (req, res) => {
  try {
    console.log('Testing passphrase mission assignments...');
    console.log('Using Vercel Postgres database');
    console.log('POSTGRES_URL set:', !!process.env.POSTGRES_URL);
    console.log('DATABASE_URL set:', !!process.env.DATABASE_URL);
    
    // Reset passphrase_missions to available status
    await executeQuery(`
      UPDATE passphrase_missions 
      SET completed = false, assigned_receiver = null, assigned_sender_1 = null, 
          assigned_sender_2 = null, previous_receivers = array[]::integer[], 
          previous_senders = array[]::integer[]
    `);
    
    // Get all users who are present
    const usersResult = await executeQuery('SELECT id, team, firstname, lastname FROM users WHERE ishere = true ORDER BY id');
    const users = (usersResult.rows || usersResult);
    
    if (users.length === 0) {
      return res.status(400).json({ error: 'No users available' });
    }
    
    // Get available passphrase missions
    const passphraseMissionsResult = await executeQuery('SELECT * FROM passphrase_missions WHERE assigned_receiver IS NULL AND assigned_sender_1 IS NULL AND assigned_sender_2 IS NULL ORDER BY RANDOM()');
    const availablePassphraseMissions = (passphraseMissionsResult.rows || passphraseMissionsResult);
    
    console.log(`Found ${users.length} users and ${availablePassphraseMissions.length} available passphrase missions`);
    
    const assignments = [];
    const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
    
    // Assign passphrase missions one by one
    for (const mission of availablePassphraseMissions) {
      if (users.length < 3) {
        console.log(`Not enough users (${users.length}) to assign passphrase mission ${mission.id}`);
        break;
      }
      
      // Pick a random user as receiver
      const receiver = pick(users);
      const remainingUsers = users.filter(u => u.id !== receiver.id);
      
      if (remainingUsers.length < 2) {
        console.log(`Not enough remaining users to assign senders for mission ${mission.id}`);
        break;
      }
      
      // Pick 2 random senders
      const sender1 = pick(remainingUsers);
      const remainingAfterSender1 = remainingUsers.filter(u => u.id !== sender1.id);
      const sender2 = pick(remainingAfterSender1);
      
      console.log(`Assigning mission ${mission.id}:`);
      console.log(`  Receiver: ${receiver.id} (${receiver.firstname} ${receiver.lastname})`);
      console.log(`  Sender 1: ${sender1.id} (${sender1.firstname} ${sender1.lastname})`);
      console.log(`  Sender 2: ${sender2.id} (${sender2.firstname} ${sender2.lastname})`);
      
      // Assign receiver and senders
      const result = await executeQuery(`
        UPDATE passphrase_missions 
        SET assigned_receiver = $1, 
            assigned_sender_1 = $2,
            assigned_sender_2 = $3,
            previous_receivers = array_append(COALESCE(previous_receivers, ARRAY[]::integer[]), $1),
            previous_senders = array_append(array_append(COALESCE(previous_senders, ARRAY[]::integer[]), $2), $3)
        WHERE id = $4 RETURNING *
      `, [receiver.id, sender1.id, sender2.id, mission.id]);
      
      const updated = result.rows || result;
      const assignment = {
        mission_id: mission.id,
        mission_template: mission.passphrase_template,
        receiver: {
          id: receiver.id,
          name: `${receiver.firstname} ${receiver.lastname}`
        },
        sender_1: {
          id: sender1.id,
          name: `${sender1.firstname} ${sender1.lastname}`
        },
        sender_2: {
          id: sender2.id,
          name: `${sender2.firstname} ${sender2.lastname}`
        },
        updated_mission: updated[0]
      };
      
      assignments.push(assignment);
    }
    
    // Verify assignments by querying the database
    const verificationResult = await executeQuery('SELECT id, passphrase_template, assigned_receiver, assigned_sender_1, assigned_sender_2 FROM passphrase_missions ORDER BY id');
    const allMissions = (verificationResult.rows || verificationResult);
    
    res.json({
      message: `Assigned ${assignments.length} passphrase missions`,
      assignments: assignments,
      verification: allMissions,
      summary: {
        total_missions: allMissions.length,
        assigned_missions: allMissions.filter(m => m.assigned_receiver !== null).length,
        unassigned_missions: allMissions.filter(m => m.assigned_receiver === null).length
      }
    });
  } catch (err) {
    console.error('Error testing passphrase mission assignments:', err);
    res.status(500).json({ error: 'Failed to test passphrase mission assignments', details: err.message });
  }
});

// Assign mission to agent
app.put('/api/missions/:id/assign', async (req, res) => {
  try {
    const { id } = req.params;
    const { agentId } = req.body;
    
    // Calculate expiration time (15 minutes from now)
    const expirationTime = new Date(Date.now() + 15 * 60 * 1000);
    
    // Update mission assignment
    const result = await executeQuery(`
      UPDATE missions 
      SET assigned_agent = $1, assigned_now = true, past_assigned_agents = array_append(past_assigned_agents, $1), mission_expires = $2
      WHERE id = $3 RETURNING *
    `, [agentId, expirationTime, id]);
    
    const missions = result.rows || result;
    res.json(missions[0]);
  } catch (err) {
    console.error('Error assigning mission:', err);
    res.status(500).json({ error: 'Failed to assign mission' });
  }
});

// Complete mission
app.put('/api/missions/:id/complete', async (req, res) => {
  try {
    const { id } = req.params;
    const { successKey, teamPoints } = req.body;
    
    // Get the mission to check the success key
    const missionResult = await executeQuery('SELECT * FROM missions WHERE id = $1', [id]);
    const missions = missionResult.rows || missionResult;
    
    if (missions.length === 0) {
      return res.status(404).json({ error: 'Mission not found' });
    }
    
    const mission = missions[0];
    
    // Check if mission is already completed
    if (mission.completed) {
      return res.status(400).json({ error: 'Mission already completed' });
    }
    
    // Validate success key (case-insensitive comparison)
    const expectedKey = mission.success_key?.toLowerCase().trim();
    const providedKey = successKey?.toLowerCase().trim();
    
    if (!expectedKey || !providedKey) {
      return res.status(400).json({ error: 'Success key required' });
    }
    
    // Check if success key matches (exact match or contains expected key for flexible answers)
    const isCorrect = expectedKey === providedKey || 
                     expectedKey.includes(providedKey) || 
                     providedKey.includes(expectedKey) ||
                     (expectedKey.startsWith('[') && expectedKey.endsWith(']')); // For placeholder answers like [any codename]
    
    if (!isCorrect) {
      return res.status(400).json({ error: 'Incorrect success key' });
    }
    
    // Mark mission as completed
    await executeQuery('UPDATE missions SET completed = true, assigned_now = false WHERE id = $1', [id]);
    
    // Update team points if provided
    if (teamPoints && teamPoints.team) {
      await executeQuery('UPDATE teams SET points = points + $1 WHERE name = $2', [teamPoints.points, teamPoints.team]);
    }
    
    res.json({ message: 'Mission completed successfully' });
  } catch (err) {
    console.error('Error completing mission:', err);
    res.status(500).json({ error: 'Failed to complete mission' });
  }
});

// Get intel clues
app.get('/api/intel', async (req, res) => {
  try {
    const result = await executeQuery('SELECT * FROM intel ORDER BY id');
    res.json(result.rows || result);
  } catch (err) {
    console.error('Error fetching intel:', err);
    res.status(500).json({ error: 'Failed to fetch intel' });
  }
});

// Add intel clue
app.post('/api/intel', async (req, res) => {
  try {
    const { clueText, agentsWhoKnow } = req.body;
    const result = await executeQuery(
      'INSERT INTO intel (clue_text, agents_who_know) VALUES ($1, $2) RETURNING *',
      [clueText, agentsWhoKnow || []]
    );
    const intels = result.rows || result;
    res.json(intels[0]);
  } catch (err) {
    console.error('Error adding intel:', err);
    res.status(500).json({ error: 'Failed to add intel' });
  }
});

// Log login attempt
app.post('/api/logs/login', async (req, res) => {
  try {
    const { agentName, success, ipAddress, userAgent } = req.body;
    const result = await executeQuery(
      'INSERT INTO login_logs (agent_name, success, ip_address, user_agent, timestamp) VALUES ($1, $2, $3, $4, NOW()) RETURNING *',
      [agentName, success, ipAddress, userAgent]
    );
    const logs = result.rows || result;
    res.json(logs[0]);
  } catch (err) {
    console.error('Error logging login attempt:', err);
    res.status(500).json({ error: 'Failed to log login attempt' });
  }
});

// Authentication endpoint
app.post('/api/auth/login', async (req, res) => {
  try {
    const { alias, passphrase } = req.body;
    
    // Get user from database using either alias_1 or alias_2
    const userResult = await executeQuery(
      'SELECT id, firstname, lastname, team, alias_1, alias_2, passphrase FROM users WHERE (alias_1 = $1 OR alias_2 = $1) AND ishere = true',
      [alias]
    );
    
    const users = userResult.rows || userResult;
    if (users.length === 0) {
      // User not found
      await executeQuery(
        'INSERT INTO login_logs (agent_name, success, ip_address, user_agent, timestamp) VALUES ($1, $2, $3, $4, NOW())',
        [alias, false, req.ip, req.get('User-Agent')]
      );
      return res.json({ success: false, message: 'Invalid credentials' });
    }
    
    const user = users[0];
    
    // Check passphrase (case-insensitive)
    if (user.passphrase.toLowerCase().trim() === passphrase.toLowerCase().trim()) {
      // Passphrase correct
      await executeQuery(
        'INSERT INTO login_logs (agent_name, success, ip_address, user_agent, timestamp) VALUES ($1, $2, $3, $4, NOW())',
        [alias, true, req.ip, req.get('User-Agent')]
      );
      res.json({ 
        success: true, 
        message: 'Authentication successful',
        user: {
          id: user.id,
          firstname: user.firstname,
          lastname: user.lastname,
          team: user.team,
          alias_1: user.alias_1,
          alias_2: user.alias_2,
          codename: `${user.alias_1} ${user.alias_2}` // For backward compatibility
        }
      });
    } else {
      // Passphrase incorrect
      await executeQuery(
        'INSERT INTO login_logs (agent_name, success, ip_address, user_agent, timestamp) VALUES ($1, $2, $3, $4, NOW())',
        [alias, false, req.ip, req.get('User-Agent')]
      );
      res.json({ success: false, message: 'Invalid credentials' });
    }
    
  } catch (err) {
    console.error('Authentication error:', err);
    res.status(500).json({ error: 'Authentication failed' });
  }
});

// Get login statistics
app.get('/api/logs/stats', async (req, res) => {
  try {
    const result = await executeQuery(`
      SELECT 
        COUNT(*) as total_attempts,
        COUNT(CASE WHEN success = true THEN 1 END) as successful_logins,
        COUNT(CASE WHEN success = false THEN 1 END) as failed_attempts
      FROM login_logs
    `);
    const stats = result.rows || result;
    res.json(stats[0]);
  } catch (err) {
    console.error('Error fetching login stats:', err);
    res.status(500).json({ error: 'Failed to fetch login statistics' });
  }
});

// Health check endpoint
app.get('/api/health', (req, res) => {
  res.json({ status: 'OK', timestamp: new Date().toISOString() });
});

// Simple test endpoint
app.get('/api/test', (req, res) => {
  console.log('Test endpoint hit!');
  res.json({ message: 'Server is working!', timestamp: new Date().toISOString() });
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
